server:
  port: 8088
#mybatis 配置
mybatis:
  type-aliases-package: com.rtst.dhjc.entity
  mapper-locations: classpath:mapper/*Mapper.xml
# mysql 配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rtstdhjc?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abc123
    #连接池配置
    druid:
      initial-size: 5
      max-active: 50
      min-idle: 1
      max-wait: 6000
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 30000
    password: abc123

#配置控制台输出执行的sql语句
logging:
  level:
    com.rtst.dhjc.repository: DEBUG
    org:
      hibernate:
        SQL: DEBUG
pagehelper:
  helperDialect: mysql
  #启用合理化，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  pageSizeZero: true

#Swagger 配置
swagger:
  title: 动环监测API文档
  desc: 动环监测API文档
  version: 1.0
  termsOfServiceUrl: javascript:void(0)
  license: Apache 2.0
  licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
  basePackage: com.rtst.dhjc
  enable: true
